import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { AlertTriangle, ArrowRight, Building2, Check, KeyRound, Landmark, LoaderCircle, MailCheck, Phone, Shield, ShieldCheck, UserRound } from 'lucide-react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from './auth'
import { AccountStatus, AuditLogItem, errorMessage, RegisterPayload, Role, services, User } from './lib/api'
import { toast } from 'sonner'

const roleNames:Record<Role,string>={citizen:'Citizen',police:'Police Officer',bank:'Bank',telecom_provider:'Telecom Provider',administrator:'Administrator'}
const dashboardFor=(role:Role)=>role==='administrator'?'/admin/users':'/dashboard'

function Brand(){
  return <Link to="/" className="auth-brand"><span><ShieldCheck/></span><b>Shield<em>IQ</em><small>DIGITAL PUBLIC SAFETY</small></b></Link>
}

function AuthFrame({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){
  return <main className="auth-page"><aside className="auth-aside"><Brand/><div><span>IDENTITY & ACCESS MANAGEMENT</span><h1>Security starts with<br/><em>trusted identity.</em></h1><p>Protected access for citizens, law enforcement, banks and critical infrastructure partners.</p></div><small>JWT PROTECTED • ROLE-BASED • AUDIT LOGGED</small></aside><section className="auth-content"><div className="auth-card"><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></main>
}

export function LoginPage(){
  const [email,setEmail]=useState('admin@shieldiq.gov.in'),[password,setPassword]=useState('ShieldIQ!2026')
  const [remember,setRemember]=useState(false),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const {login,user}=useAuth();const navigate=useNavigate();const location=useLocation()
  useEffect(()=>{if(user)navigate(dashboardFor(user.role),{replace:true})},[user,navigate])
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const current=await login(email,password,remember);toast.success('Login successful',{description:`Welcome back, ${current.full_name}`});navigate((location.state as {from?:string})?.from||dashboardFor(current.role),{replace:true})}catch(err){const message=errorMessage(err);setError(message);toast.error('Invalid credentials',{description:message})}finally{setBusy(false)}}
  return <AuthFrame title="Welcome back" subtitle="Sign in to your secure ShieldIQ workspace."><form className="auth-form" onSubmit={submit}><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<div className="auth-password"><input required type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'}</button></div></label><div className="auth-options"><label><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember this device</label><Link to="/forgot-password">Forgot password?</Link></div>{error&&<div className="auth-error"><AlertTriangle/>{error}</div>}<button className="primary auth-submit" disabled={busy}>{busy?<><LoaderCircle className="spin"/> Authenticating…</>:<>Sign in securely <ArrowRight/></>}</button><p className="auth-switch">New to ShieldIQ? <Link to="/signup">Create an account</Link></p></form></AuthFrame>
}

const signupSchema=z.object({
  full_name:z.string().min(2,'Enter your full name'),email:z.email('Enter a valid email'),
  phone:z.string().min(8,'Enter a valid phone number'),password:z.string().min(10,'Use at least 10 characters').regex(/[A-Z]/,'Add an uppercase letter').regex(/[a-z]/,'Add a lowercase letter').regex(/\d/,'Add a number').regex(/[^A-Za-z0-9]/,'Add a symbol'),
  confirm_password:z.string(),state:z.string().optional(),district:z.string().optional(),organization:z.string().optional(),employee_id:z.string().optional(),badge_number:z.string().optional(),police_station:z.string().optional(),department:z.string().optional(),rank:z.string().optional(),branch:z.string().optional(),accept_terms:z.literal(true,{error:'Accept the terms to continue'})
}).refine(v=>v.password===v.confirm_password,{path:['confirm_password'],message:'Passwords do not match'})
type SignupFields=z.infer<typeof signupSchema>

export function SignupPage(){
  const [role,setRole]=useState<Role|null>(null),[busy,setBusy]=useState(false),[serverError,setServerError]=useState('')
  const navigate=useNavigate();const {register,handleSubmit,formState:{errors}}=useForm<SignupFields>({resolver:zodResolver(signupSchema),defaultValues:{accept_terms:true}})
  const submit=handleSubmit(async values=>{if(!role)return;setBusy(true);setServerError('');try{const user=await services.auth.register({...values,role,preferred_language:'English'} as RegisterPayload);sessionStorage.setItem('shieldiq_pending_user',JSON.stringify({email:user.email,phone:user.phone,role:user.role,token:user.demo_verification_token,otp:user.demo_otp}));toast.success('Account created',{description:'Complete email and phone verification to continue.'});navigate('/verify-account')}catch(err){const message=errorMessage(err);setServerError(message);toast.error('Account creation failed',{description:message})}finally{setBusy(false)}})
  const roles:[Role,React.ReactNode,string][]=[['citizen',<UserRound/>,'Personal fraud protection'],['police',<Shield/>,'Law enforcement workspace'],['bank',<Landmark/>,'Financial intelligence'],['telecom_provider',<Phone/>,'Telecom threat operations']]
  if(!role)return <AuthFrame title="Choose your role" subtitle="Your role determines verification and workspace access."><div className="signup-roles">{roles.map(([value,icon,text])=><button key={value} onClick={()=>setRole(value)}>{icon}<b>{roleNames[value]}</b><small>{text}</small><ArrowRight/></button>)}</div><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></AuthFrame>
  return <AuthFrame title={`Create ${roleNames[role]} account`} subtitle={role==='citizen'?'Verify your email and phone to activate instantly.':'Agency accounts require identity verification and administrator approval.'}><form className="auth-form signup-form" onSubmit={submit}><button type="button" className="back-role" onClick={()=>setRole(null)}>← Change role</button><div className="auth-grid"><Field label="Full name" name="full_name" register={register} error={errors.full_name?.message}/><Field label="Email address" name="email" type="email" register={register} error={errors.email?.message}/><Field label="Mobile number" name="phone" register={register} error={errors.phone?.message}/><Field label="State" name="state" register={register}/><Field label="District" name="district" register={register}/>{role==='police'&&<><Field label="Badge number" name="badge_number" register={register}/><Field label="Police station" name="police_station" register={register}/><Field label="Department" name="department" register={register}/><Field label="Rank" name="rank" register={register}/></>}{(role==='bank'||role==='telecom_provider')&&<><Field label="Organization" name="organization" register={register}/><Field label="Employee ID" name="employee_id" register={register}/><Field label="Branch / office" name="branch" register={register}/><Field label="Department" name="department" register={register}/></>}<Field label="Password" name="password" type="password" register={register} error={errors.password?.message}/><Field label="Confirm password" name="confirm_password" type="password" register={register} error={errors.confirm_password?.message}/></div><label className="terms"><input type="checkbox" {...register('accept_terms')}/> I accept the Terms of Use and Privacy Policy.</label>{errors.accept_terms&&<small className="field-error">{errors.accept_terms.message}</small>}{serverError&&<div className="auth-error"><AlertTriangle/>{serverError}</div>}<button className="primary auth-submit" disabled={busy}>{busy?'Creating secure identity…':'Create account'} <ArrowRight/></button></form></AuthFrame>
}

function Field({label,name,type='text',register,error}:{label:string;name:keyof SignupFields;type?:string;register:ReturnType<typeof useForm<SignupFields>>['register'];error?:string}){
  return <label>{label}<input type={type} {...register(name)}/>{error&&<small className="field-error">{error}</small>}</label>
}

export function VerifyAccountPage(){
  const [params]=useSearchParams();const saved=useMemo(()=>{try{return JSON.parse(sessionStorage.getItem('shieldiq_pending_user')||'{}')}catch{return {}}},[])
  const [emailToken,setEmailToken]=useState(params.get('token')||saved.token||''),[phone,setPhone]=useState(saved.phone||''),[otp,setOtp]=useState(saved.otp||''),[emailDone,setEmailDone]=useState(false),[phoneDone,setPhoneDone]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const act=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage('');try{await fn();setMessage(success);toast.success(success)}catch(e){const message=errorMessage(e);setMessage(message);toast.error('Verification failed',{description:message})}finally{setBusy(false)}}
  const verifyEmail=()=>act(async()=>{await services.auth.verifyEmail(emailToken);setEmailDone(true)},'Email verified successfully.')
  const send=()=>act(async()=>{const result=await services.auth.sendOtp(phone);if(result.otp)setOtp(result.otp)},'Verification code sent.')
  const verifyPhone=()=>act(async()=>{await services.auth.verifyOtp(phone,otp);setPhoneDone(true)},saved.role==='citizen'?'Account activated. You may sign in now.':'Identity verified. Your account is awaiting administrator approval.')
  return <AuthFrame title="Verify your identity" subtitle="Complete both checks to protect your ShieldIQ account."><div className="verify-stack"><section className={emailDone?'done':''}><span>{emailDone?<Check/>:<MailCheck/>}</span><div><b>Email verification</b><p>Open the verification link sent to {saved.email||'your email'}, or paste its secure token.</p><input value={emailToken} onChange={e=>setEmailToken(e.target.value)} placeholder="Verification token"/><button disabled={!emailToken||busy} onClick={verifyEmail}>Verify email</button></div></section><section className={phoneDone?'done':''}><span>{phoneDone?<Check/>:<Phone/>}</span><div><b>Phone OTP</b><p>Confirm the mobile number attached to this identity.</p><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91…"/><div className="otp-row"><input inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="6-digit OTP"/><button onClick={send} disabled={!phone||busy}>Send code</button><button onClick={verifyPhone} disabled={otp.length!==6||busy}>Verify</button></div></div></section>{message&&<div className="auth-notice">{message}</div>}<Link className="primary auth-link-button" to="/login">Continue to sign in <ArrowRight/></Link></div></AuthFrame>
}

export function ForgotPasswordPage(){
  const [email,setEmail]=useState(''),[otp,setOtp]=useState(''),[password,setPassword]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const request=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await services.auth.forgotPassword(email);setSent(true);if(r.otp)setOtp(r.otp);setMessage(r.message);toast.success('Reset code requested')}catch(err){const message=errorMessage(err);setMessage(message);toast.error('Reset request failed',{description:message})}finally{setBusy(false)}}
  const reset=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{setMessage((await services.auth.resetPassword(email,otp,password)).message);toast.success('Password reset complete');setTimeout(()=>location.assign('/login'),900)}catch(err){const message=errorMessage(err);setMessage(message);toast.error('Password reset failed',{description:message})}finally{setBusy(false)}}
  return <AuthFrame title="Recover your account" subtitle="A time-limited reset code will be sent to your verified email."><form className="auth-form" onSubmit={sent?reset:request}><label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={sent}/></label>{sent&&<><label>Reset code<input required inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/></label><label>New password<input required type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></label></>}{message&&<div className="auth-notice">{message}</div>}<button className="primary auth-submit" disabled={busy}>{sent?'Reset password':'Send reset code'} <ArrowRight/></button><p className="auth-switch"><Link to="/login">Return to sign in</Link></p></form></AuthFrame>
}

export function AdminUsersPage({shell}:{shell:(props:{children:React.ReactNode;title:string;subtitle:string})=>React.ReactNode}){
  const [users,setUsers]=useState<User[]>([]),[filter,setFilter]=useState<AccountStatus|''>('pending'),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const [auditLogs,setAuditLogs]=useState<AuditLogItem[]>([])
  const load=async()=>{try{const [identities,audits]=await Promise.all([services.auth.adminUsers(filter||undefined),services.auth.auditLogs({limit:100})]);setUsers(identities);setAuditLogs(audits);setError('')}catch(e){setError(errorMessage(e))}}
  useEffect(()=>{void load()},[filter])
  const action=async(user:User,verb:'approve'|'reject'|'block'|'unblock')=>{setBusy(user.id);try{await services.auth.adminAction(user.id,verb);toast.success(`User ${{approve:'approved',reject:'rejected',block:'blocked',unblock:'unblocked'}[verb]}`,{description:user.email});await load()}catch(e){const message=errorMessage(e);setError(message);toast.error('Admin action failed',{description:message})}finally{setBusy('')}}
  return <>{shell({title:'Identity Administration',subtitle:'Approve agency identities, enforce access policy, and monitor account state.',children:<div className="admin-stack"><article className="panel admin-users"><div className="admin-toolbar"><div><Building2/><b>Registered identities</b></div><select value={filter} onChange={e=>setFilter(e.target.value as AccountStatus|'')}><option value="">All statuses</option><option>pending</option><option>verified</option><option>rejected</option><option>blocked</option></select></div>{error&&<div className="auth-error"><AlertTriangle/>{error}</div>}<div className="table-scroll"><table><thead><tr><th>IDENTITY</th><th>ROLE</th><th>VERIFICATION</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.full_name}</b><small>{user.email}<br/>{user.phone||'No phone'}</small></td><td>{roleNames[user.role]}</td><td><span className={user.email_verified?'ok':'wait'}>Email</span> <span className={user.phone_verified?'ok':'wait'}>Phone</span></td><td><span className={`account-status ${user.account_status}`}>{user.account_status}</span></td><td><div className="admin-actions">{user.account_status==='pending'&&<><button disabled={busy===user.id} onClick={()=>action(user,'approve')}>Approve</button><button disabled={busy===user.id} onClick={()=>action(user,'reject')}>Reject</button></>}{user.account_status==='verified'&&<button disabled={busy===user.id} onClick={()=>action(user,'block')}>Block</button>}{user.account_status==='blocked'&&<button disabled={busy===user.id} onClick={()=>action(user,'unblock')}>Unblock</button>}</div></td></tr>)}</tbody></table>{!users.length&&<div className="empty-inline">No identities match this status.</div>}</div></article><article className="panel audit-table"><div className="admin-toolbar"><div><ShieldCheck/><b>Enterprise audit log</b></div><button onClick={()=>void load()}>Refresh</button></div><div className="table-scroll"><table><thead><tr><th>USER</th><th>ACTION</th><th>RESOURCE</th><th>TIMESTAMP</th><th>IP</th><th>STATUS</th></tr></thead><tbody>{auditLogs.map(item=><tr key={item.id}><td><b>{item.user}</b><small>{item.email||'System identity'}</small></td><td>{item.action.replaceAll('.',' › ')}</td><td>{item.resource}</td><td>{new Date(item.timestamp).toLocaleString()}</td><td>{item.ip_address||'Internal'}</td><td><span className={`audit-status ${item.status}`}>{item.status}</span></td></tr>)}</tbody></table>{!auditLogs.length&&<div className="empty-inline">No audit events recorded yet.</div>}</div></article></div>})}</>
}
